version: 0.0
os: linux

files:
  - source: html/
    destination: /var/www/html/
    overwrite: true   # ensures all files are replaced

hooks:
  BeforeInstall:
    - location: scripts/clean_html.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/restart_apache.sh
      timeout: 300
      runas: root
