version: 0.0
os: linux

files:
  - source: html/
    destination: /var/www/html/
    overwrite: true  

hooks:
  AfterInstall:
    - location: scripts/restart_apache.sh
      timeout: 300
      runas: root
